// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwhywAmGoT4Zc3MQwZapw3HZMXchRDFNY',
    appId: '1:1065650605834:web:8a267290f45a091563b4f3',
    messagingSenderId: '1065650605834',
    projectId: 'uniloot',
    authDomain: 'uniloot.firebaseapp.com',
    storageBucket: 'uniloot.appspot.com',
    measurementId: 'G-N4TVLNJG9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2262sVrO0OYXtgbQO1NIeTzSH1piLytE',
    appId: '1:1065650605834:android:2a0ae1e3c356830b63b4f3',
    messagingSenderId: '1065650605834',
    projectId: 'uniloot',
    storageBucket: 'uniloot.appspot.com',
  );
}
